### ISSUE TITLE
Design Web Design

### ISSUE THREAD

**Issue by AbhishekJoshi93** [clubgamma/CryptoHunter#2]
**Tools you can used for web design.**

_1. Adobe XD
2. Figma_ 

* You can use your preferred tools for the same.

**Take below attachment as an inspiration for designing UI for cryptoHunter.**

![UI](https://user-images.githubusercontent.com/53364533/94902412-bbb93180-04b5-11eb-821d-9ee2be39f59a.jpeg)

**For further reference use documentation of project.**

**Comment by arc3us** [comment]
If you only need a mockup, I'd like to take this

**Comment by AbhishekJoshi93** [comment]
Go for it @arc3us 😇

**Comment by zorione** [comment]
Is this issue still available?
i want to work on this

**Comment by AbhishekJoshi93** [comment]
@zorione Yes it is still available you can work on it.
